### ISSUE TITLE
initial help to start script?

### ISSUE THREAD

**Issue by pcace** [halprin/lightroom-export#1]
Hi there,

i am trying to understand how your script works. Can you give me a very brief how to use and how it works?

Thank you so much

EDIT: this is what i am getting on a test database, but when looking a the sql file, i cannot really find anything wrong.. what am i missing?: 

```
python3 main.py /Users/user/Desktop/test/test.lrcat
Transitioning /Users/user/Desktop/test/test.lrcat
Traceback (most recent call last):
  File "/Volumes/Data/Downloads/Misc/lightroom-export-master/LightroomExport/main.py", line 797, in <module>
    main(database_path)
  File "/Volumes/Data/Downloads/Misc/lightroom-export-master/LightroomExport/main.py", line 286, in main
    photo_details = get_all_photo_details(db_connection)
  File "/Volumes/Data/Downloads/Misc/lightroom-export-master/LightroomExport/main.py", line 423, in get_all_photo_details
    'name': extract_name_from_xmp(xmp),
  File "/Volumes/Data/Downloads/Misc/lightroom-export-master/LightroomExport/main.py", line 444, in extract_name_from_xmp
    xml_tree = ElementTree.fromstring(xmp)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```

**Comment by halprin** [comment]
I'm trying to refresh my memory of this.  I'm looking at XMP data that is stored in the Lightroom catalog to extract the name of the image.  Specifically it is in the `Adobe_AdditionalMetadata` table, `xmp` column.  You can view the SQL query [here](https://github.com/halprin/lightroom-export/blob/575d49fa31d3a795a7bacd970b62a672113e88c0/LightroomExport/main.py#L407-L419).  XMP uses XML for its format, so I parse it and look for a specific tag inside of it that contains the name.  You can see that code [here](https://github.com/halprin/lightroom-export/blob/575d49fa31d3a795a7bacd970b62a672113e88c0/LightroomExport/main.py#L443-L448).  Based on the stack trace you supplied, it seems that the XML is seemingly not well formed.  I'd check the table and column I mentioned above and see if there is data there and if it seems to be valid XML.

**Comment by pcace** [comment]
Hi, thank you so much, 

i got it working, but have some very strange problems: 
there are files, wich stop the import process for no obvious reason. After i had realized, that under catalina apple photos is running in a kind of sandbox, thus there is a workaround necessary for the applescript to import: 

```
import_photo_apple_script = applescript.AppleScript("""on run photo_path
set theList to photo_path
set l to {}
repeat with f in theList
	set l to l & (POSIX file f)
end repeat

tell application "Photos"
	import l with skip check duplicates
end tell
end run""")
```

without this, i would just get an errormessage from photos that i do not have the required previleges to import this file. Strangely now, the script is doing its job, but stops at one perticular file, after an hour of flawless running. 

this is how the folder looks like where the file (DSC_3515.dng) is located: 

```
-rwxr-xr-x    1 user  admin    4741876 20 Aug 10:20 DSC_3509.dng
-rwxr-xr-x    1 user  admin    4426092 20 Aug 10:20 DSC_3510.dng
-rwxr-xr-x    1 user  admin    4008214 20 Aug 10:20 DSC_3511.dng
-rwxr-xr-x    1 user  admin    3764566 20 Aug 10:20 DSC_3512.dng
-rwxr-xr-x    1 user  admin    4450850 20 Aug 10:20 DSC_3513.dng
-rwxr-xr-x    1 user  admin    4867488 20 Aug 10:20 DSC_3515.dng
-rwxr-xr-x    1 user  admin    4687060 20 Aug 10:20 DSC_3517.dng
-rwxr-xr-x    1 user  admin    5117372 20 Aug 10:20 DSC_3526.dng
-rwxr-xr-x    1 user  admin    4625772 20 Aug 10:20 DSC_3527.dng
-rwxr-xr-x    1 user  admin    5136948 20 Aug 10:20 DSC_3528.dng
```
there is no .* file, nor anything else in that folder. every other image in that folder was successfully transfered. 
Have you ever had that problem? or any Idea, what the problem could be?

Thank you so much for your help,

pcace

![Bildschirmfoto 2021-08-20 um 16 11 47](https://user-images.githubusercontent.com/1011875/130246859-1111711a-6ae4-465d-8ccc-92ea9642419d.png)
(it sais: could not be copied, because you do not have the right privileges - exact the same error i had earlier when not having this little tweak in the code as shown above...)


EDIT: easier, but same problem: 

```
import_photo_apple_script = applescript.AppleScript("""on run photo_path
set f to POSIX file photo_path
tell application "Photos"
	import f with skip check duplicates
end tell
end run""")
```

**Comment by halprin** [comment]
That does ring a bell, but for the life of me I can't remember what I did to overcome the problem. I _might_ be able to help more in a week when I'm back in front of my main computer.

Does that image import into Photos when you manually drag and drop it into Photos? Or does it successfully import into Photos when you modify the ApeScript to import just that photo and manually run it?

**Comment by pcace** [comment]
Hi,

i have played around with the Script yesterday, but could not find a working solution. no matter what i do the problem stays the same:

- i run the py script,
- all the folders/Selections get created in Photos
- it starts importing pictures
- at some random point it stops with this error message: 
```
Importing /Volumes/Lightroom/Lightroom/2006/2006-10-09/DSC_3596.dng
Adding photo to album(s) [84713]
Importing /Volumes/Lightroom/Lightroom/2006/2006-10-09/DSC_3597.dng
Adding photo to album(s) [84713]
Importing /Volumes/Lightroom/Lightroom/2006/2006-10-09/DSC_3598.dng
Traceback (most recent call last):
  File "/Volumes/Data/Nextcloud/Make/GitHub/LRtoFoto/main.py", line 695, in <module>
    main(database_path)
  File "/Volumes/Data/Nextcloud/Make/GitHub/LRtoFoto/main.py", line 254, in main
    import_photos(photo_details, album_conversion, stack_details)
  File "/Volumes/Data/Nextcloud/Make/GitHub/LRtoFoto/main.py", line 408, in import_photos
    photos_photo_id = import_photo(photo_info['datei'])
  File "/Volumes/Data/Nextcloud/Make/GitHub/LRtoFoto/main.py", line 501, in import_photo
    return result[0][applescript.AEType(b'seld')]
TypeError: 'AEType' object is not subscriptable
johannes@MacPro LRtoFoto % 
```
![Bildschirmfoto 2021-08-22 um 12 52 38](https://user-images.githubusercontent.com/1011875/130352484-8344a319-59a2-4d90-8e3d-0625c93ff71e.png)


Interestingly, when i then try to import that same image where Apple Photos crashed, via applescript like so:

```
set f to POSIX file "/Volumes/Lightroom/Lightroom/2006/2006-11-18/RIMG0007.JPG"
tell application "Photos"
	import f with skip check duplicates
end tell
```
It does the same: Photos cannot import the picture:
![Bildschirmfoto 2021-08-22 um 12 56 47](https://user-images.githubusercontent.com/1011875/130352576-3a8665fb-f8a5-45c3-ac22-d21ff4c59d0c.png)

When i restart Photos tho, then it imports just fine!!

![Bildschirmfoto 2021-08-22 um 13 00 01](https://user-images.githubusercontent.com/1011875/130352652-fb9f706f-88b8-4032-aafd-b5b5e101c4f1.png)


In an act of despiration, i added two lines to restart Photos before every image (stupid, i know...) but even this did not help: after a night of importing, it did crash with the same errormessage. 

So if you have any idea on how i could solve that problem, or even direct me in a way where that error could come from it would just be great!!!

Thank you so much for your help!!
